# Generated by Django 4.2.11 on 2024-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0009_rename_dispatchersettings_dispatchersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchersetting',
            name='trapi_version',
            field=models.CharField(default='1.5', max_length=28),
        ),
    ]
