apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "chp-api.fullname" . }}-secret
  labels:
    {{- include "chp-api.labels" . | nindent 4 }}
data:
  sql_database: {{ .Values.db.database }}
  sql_username: {{ .Values.db.username }}
  sql_password: {{ .Values.db.password }}
  secret_key: {{ .Values.app.secret_key }}